# Generated by Django 4.1 on 2022-08-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('temperature', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
    ]
